apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: h5-openim
  labels:
    app: h5-openim
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,operationid,token,operationID"
    nginx.ingress.kubernetes.io/cors-expose-headers: "Content-Length,Content-Type"
    nginx.ingress.kubernetes.io/cors-max-age: "1728000"
    # --- WebSocket 支持配置 ---
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
  - host: h5-v1-openim.36x9.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: h5-openim
            port:
              number: 80
